export const finantialEntities: { [key: number]: { description: string } } = {
  1: { description: 'BBVA' },
  2: { description: 'Banco Consorcio' },
  3: { description: 'Banco de Chile' },
  4: { description: 'Banco Estado' },
  5: { description: 'Banco Falabella' },
  6: { description: 'Banco internacional' },
  7: { description: 'Banco Itaú' },
  8: { description: 'Banco Ripley' },
  9: { description: 'Banco Santander' },
  10: { description: 'Scotiabank' },
  11: { description: 'Banco Security' },
  12: { description: 'Bancobice' },
  13: { description: 'Coopeuch' },
  14: { description: 'Banco Corpbanca' },
  15: { description: 'HSBC' },
  16: { description: 'Mercado pago' },
  17: { description: 'MUFG' },
  18: { description: 'Los Heroes' },
  19: { description: 'Tenpo' },
};
