# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - te-apoyo-api-v2

on:
  push:
    branches:
      - master-te-apoyo
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://teapoyoapiv2acr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_29d34c8cf5d04c30b49b5519c1140ea6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5b99274100414b07bd62ce70fcc86a64 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: teapoyoapiv2acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_29d34c8cf5d04c30b49b5519c1140ea6 }}/teapoyoapiv2acr:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'te-apoyo-api-v2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a49def8e668c4777a9e506b2dcbc3354 }}
        images: 'teapoyoapiv2acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_29d34c8cf5d04c30b49b5519c1140ea6 }}/teapoyoapiv2acr:${{ github.sha }}'